{% set name = "sphinx-pdj-theme" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 376fa8ee574ce49fe85c31eda2da581d44af92b676234ba5eed3d3cd049931b2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=65
    - wheel >=0.38
    - pip
  run:
    - python >=3.6

test:
  imports:
    - sphinx_pdj_theme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jucacrispim/sphinx_pdj_theme
  summary: A cool theme for sphinx documentation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
