{% set name = "sphinx-pdj-theme" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx-pdj-theme-{{ version }}.tar.gz
  sha256: d656119266630f2eee376ddfcd79c7f88ecf1be2a91df0f25da98af35edafcda

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=65
    - wheel >=0.38
    - pip
  run:
    - python >=3.6

test:
  imports:
    - sphinx_pdj_theme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jucacrispim/sphinx_pdj_theme
  summary: A cool theme for sphinx documentation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
