{% set name = "sphinx-pdj-theme" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2fa092087aceab4015f583ef02812a586dd46f45923c71f7f361ecd3b9554e3f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=65
    - wheel >=0.38
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - sphinx_pdj_theme
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jucacrispim/sphinx_pdj_theme
  summary: A cool theme for sphinx documentation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
